CREATE TABLE EMP_HW (
    EMPNO NUMBER(4)
    , ENAME NVARCHAR2(10)
    , JOB NVARCHAR2(9)
    , MGR NUMBER(4)
    , HIREDATE DATE
    , SAL NUMBER(7,2)
    , COMM NUMBER(7,2)
    , DEPTNO NUMBER(2)
);
 
 ALTER TABLE EMP_HW ADD BIGO NVARCHAR2(20);
 TRUNCATE TABLE EMP_HW;
 
 -- NULL값불가능 설정
ALTER TABLE EMP_HW MODIFY EMPNO NUMBER(4) NOT NULL;
ALTER TABLE EMP_HW MODIFY ENAME NVARCHAR2(10) NOT NULL;
ALTER TABLE EMP_HW MODIFY JOB NVARCHAR2(9) NOT NULL;
ALTER TABLE EMP_HW MODIFY MGR NUMBER(4) NOT NULL;
ALTER TABLE EMP_HW MODIFY HIREDATE DATE NOT NULL;
ALTER TABLE EMP_HW MODIFY SAL NUMBER(7,2) NOT NULL;
 
 ALTER TABLE EMP_HW RENAME COLUMN BIGO TO REMAKE;
 
 -- INSERT : 값 넣기
/* INSERT 테이블명 (컬럼명1, 컬럼명2, 컬럼명3)
VALUES (값1, 값2, 값3); */
INSERT INTO EMP_HW 
    (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO, REMAKE)
VALUES 
    (1, '이름', '부서', 2, '2000-01-01', 100, 100, 30, '비고');
    
-- UPDATE : 테이블 내용 수정
UPDATE 테이블명 SET 컬럼명 = 값, 컬럼명 = 값 ..........
WHERE 컬럼명 = 값; -- 조건을 찿아 위에 명령문대로 변경

UPDATE EMP_HW SET ENAME = '홍길동'
WHERE EMPNO = 1;
    
-- DELETE : 데이터 행 삭제
DELETE 테이블명
WHERE 컬럼명 = 값; -- 조건을 찿아 해당하면 삭제 

DELETE EMP_HW 
WHERE EMPNO = 2;

SELECT * FROM EMP_HW;