CREATE TABLE MEMBER ( -- 가입자정보
	MEM_IDX NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY -- 프라이머리 키
	, IS_ADMIN NUMBER(1) DEFAULT 0 CONSTRAINT IS_ADMIN_NN NOT NULL -- 관리자여부 확인 기본값은 0 (0 : 사용자)(1 : 관리자)
	, USER_ID NVARCHAR2(10) CONSTRAINT USER_ID_UNI UNIQUE NOT NULL -- 사용자 아이디 유니크, NULL 불가
	, USER_PW CHAR(64) CONSTRAINT USER_PW_NN NOT NULL -- 패스워드, NULL 불가
	, USER_NAME NVARCHAR2(10) CONSTRAINT USER_NAME_NN NOT NULL -- 사용자이름, NULL 불가
	, EMAIL NVARCHAR2(30) CONSTRAINT EMAIL_NN NOT NULL -- 이메일, NULL 불가
	, PHONE_NUM NUMBER(13) CONSTRAINT PHONE_NUM_NN NOT NULL -- 전화번호, NULL 불가
	, REG_DATE DATE DEFAULT SYSDATE CONSTRAINT REG_DATE_NN NOT NULL -- 가입일, 현제시간기본값, NULL 불가
	, DROP_DATE DATE DEFAULT SYSDATE CONSTRAINT DROP_DATE_NN NOT NULL -- 탈퇴일, 현제시간기본값, NULL 불가
	, USER_ADDR NVARCHAR2(50) -- 거주지주소, NULL값 가능
	, DROP_YN CHAR(1) DEFAULT 'N' CONSTRAINT DROP_YN_NN NOT NULL -- 탈퇴여부, 기본값 N (N : 정상)(Y : 탈퇴준비기간)
	, EMAIL_AUTH CHAR(1) DEFAULT 'N' CONSTRAINT EMAIL_AUTH_NN NOT NULL -- 이메일 인증여부, 기본값 N (N : 미인증)(Y : 인증완료)
	, EMAIL_AUTH_CODE NVARCHAR2(50) CONSTRAINT EMAIL_AUTH_CODE_NN NOT NULL -- 이메일 인증코드 발송, NULL 불가
	, BLOCK_CODE CHAR(1) DEFAULT 'N' CONSTRAINT BLOCK_CODE_NN NOT NULL -- 불량이용자 블락, 기본값 N (N : 정상)(Y : 이용자 차단)
	);

-- 데이터 저장시 비밀번호는 암호화가 필요 (해시)


CREATE TABLE FESTIVAL ( -- 축제정보
	FES_IDX NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY -- 프라이머리 키
	, AREA_CODE NUMBER(3) CONSTRAINT AREA_CODE_NN NOT NULL -- 지역코드
	, ADDR NVARCHAR2(50) CONSTRAINT ADDR_NN NOT NULL -- 축제지 주소
	, ADDR_2 NVARCHAR2(50) -- 축제지 세부주소, NULL 허용 
	, MAPX NUMBER(13,10) CONSTRAINT MAPX NOT NULL -- X좌표
	, MAPY NUMBER(13,10) CONSTRAINT MAPY NOT NULL -- Y좌표
	, START_DATE DATE CONSTRAINT START_DATE NOT NULL -- 축제 시작일
	, END_DATE DATE CONSTRAINT END_DATE NOT NULL -- 축제 종료일
	, TITLE NVARCHAR2(30) CONSTRAINT TITLE_NN NOT NULL -- 축제명
	, TEL NVARCHAR2(20) -- 축제 연락처 NULL 허용
	, IMAGE VARCHAR2(100) CONSTRAINT IMAGE_NN NOT NULL -- 축제 이미지 
	, IMAGE_2 VARCHAR2(100)  -- 축제 이미지2
	);

CREATE TABLE ACCOMMODATION ( -- 숙박시설정보
	ACC_IDX NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY -- 프라이머리 키
	, AREA_CODE NUMBER(3) CONSTRAINT AREA2_CODE_NN NOT NULL -- 지역코드
	, ADDR NVARCHAR2(50) CONSTRAINT ADDR2_NN NOT NULL -- 숙박시설 주소
	, ADDR_2 NVARCHAR2(50) -- 숙박시설 세부주소, NULL 허용 
	, MAPX NUMBER(13,10) CONSTRAINT MAPX2 NOT NULL -- X좌표
	, MAPY NUMBER(13,10) CONSTRAINT MAPY2 NOT NULL -- Y좌표
	, TITLE NVARCHAR2(30) CONSTRAINT TITLE2_NN NOT NULL -- 숙박시설명
	, TEL NVARCHAR2(20) -- 숙박시설 연락처 NULL 허용
	, IMAGE VARCHAR2(100)  -- 이미지 
	, IMAGE_2 VARCHAR2(100)  -- 이미지2
	);

CREATE TABLE BOARD (
	BOD_IDX NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY -- 프라이머리 키
	, CATE NUMBER(4) CONSTRAINT CATE_NN NOT NULL -- 게시판 구분(1000 : 공지사항, 2000 : 후기게시판, 3000 : 여행일정공유)
	, BOD_TITLE NVARCHAR2(50) CONSTRAINT BOD_TITLE_NN NOT NULL -- 게시판 제목
	, BOD_CONSTENT NVARCHAR2(2000) CONSTRAINT BOD_CONSTENT_NN NOT NULL -- 게시글 내용
	, TRAVEL_START_DATE DATE CONSTRAINT TRAVEL_START_DATE_NN NOT NULL -- 여행시작일 (여행일정공유 게시판 사용)
	, TRAVEL_END_DATE DATE CONSTRAINT TRAVEL_END_DATE_NN NOT NULL -- 여행종료일 (여행일정공유 게시판 사용)
	, VISIT DATE CONSTRAINT VISIT_NN NOT NULL -- 축제방문일 (후기게시판 사용)
	, FES_TITLE NVARCHAR2(100) CONSTRAINT FES_TITLE_NN NOT NULL -- 축제명(후기게시판), (여행일정공유) 별점적용시 데이터저장
	, ACC_TITLE NVARCHAR2(100) CONSTRAINT ACC_TITLE_NN NOT NULL -- 숙박시설명 
	, RATING NUMBER (1) CONSTRAINT RATING_NN NOT NULL -- 별점(후기게시판) 
	, REG_ID NVARCHAR2 (30) CONSTRAINT REGID_NN NOT NULL -- 등록자 ID
	, REG2_DATE DATE DEFAULT SYSDATE CONSTRAINT REG2_DATE_NN NOT NULL -- 등록일 
	, UPDATE_ID NVARCHAR2 (30) CONSTRAINT UPDATE_ID_NN NOT NULL -- 수정자 ID
	, UPDATE_DATE DATE DEFAULT SYSDATE CONSTRAINT UPDATE_DATE_NN NOT NULL --수정일
	, FILE_MST_ID NVARCHAR2 (15) 
	);

CREATE TABLE COMMENTS ( -- 댓글 저장
	COM_IDX NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY -- 프라이머리 키
	, CONTENT NVARCHAR2(500) NOT NULL -- 댓글 내용
	, REG_ID NVARCHAR2(30) NOT NULL -- 등록자 아이디
	, REG_DATE DATE DEFAULT SYSDATE NOT NULL -- 등록일
	, UPD_ID NVARCHAR2(30) NOT NULL -- 수정자 아이디
	, UPD_DATE DATE DEFAULT SYSDATE NOT NULL -- 수정일
);

CREATE TABLE BBS (
	FILE_DETAIL_ID NUMBER NOT NULL
	, FILE_MST_ID NUMBER NOT NULL
	, FILE_DEST NVARCHAR2(100)
	, FILE_NUMBER NUMBER
	, FILE_LOCATION VARCHAR2(1000) NOT NULL
	, FILE_PATH VARCHAR2(1000) NOT NULL
	, FILE_NAME VARCHAR2(255) NOT NULL
	, ORG_FILE_NAME VARCHAR2(255) NOT NULL
	, FILE_EXT VARCHAR2(2) NOT NULL
	, FILE_MIME VARCHAR2(100) NOT NULL
	, FILE_SIZE NUMBER NOT NULL
	, regID VARCHAR2(30) NOT NULL
	, regDate DATE DEFAULT SYSDATE NOT NULL
	, updID VARCHAR2(30) NOT NULL
	, updDate DATE DEFAULT SYSDATE NOT NULL
);

ALTER TABLE BOARD
ADD CONSTRAINT FK_BOARD_REG_ID
FOREIGN KEY (REG_ID)
REFERENCES MEMBER(USER_ID);

ALTER TABLE BOARD
ADD CONSTRAINT FK_BOARD_UPDATE_ID
FOREIGN KEY (UPDATE_ID)
REFERENCES MEMBER(USER_ID);

ALTER TABLE BOARD
DROP CONSTRAINT FK_BOARD_REG_ID;

