--------------------------------------------------------
--  파일이 생성됨 - 금요일-4월-11-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ACCOMMODATION
--------------------------------------------------------

  CREATE TABLE "ADMIN"."ACCOMMODATION" 
   (	"ACC_IDX" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"AREA_CODE" NUMBER(3,0), 
	"ADDR" NVARCHAR2(50), 
	"ADDR_2" NVARCHAR2(50), 
	"MAPX" NUMBER(13,10), 
	"MAPY" NUMBER(13,10), 
	"TITLE" NVARCHAR2(30), 
	"TEL" NVARCHAR2(20), 
	"IMAGE" VARCHAR2(100 BYTE), 
	"IMAGE_2" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
REM INSERTING into ADMIN.ACCOMMODATION
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index SYS_C008607
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."SYS_C008607" ON "ADMIN"."ACCOMMODATION" ("ACC_IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ACCOMMODATION
--------------------------------------------------------

  ALTER TABLE "ADMIN"."ACCOMMODATION" MODIFY ("ACC_IDX" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."ACCOMMODATION" MODIFY ("AREA_CODE" CONSTRAINT "AREA2_CODE_NN" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."ACCOMMODATION" MODIFY ("ADDR" CONSTRAINT "ADDR2_NN" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."ACCOMMODATION" MODIFY ("MAPX" CONSTRAINT "MAPX2" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."ACCOMMODATION" MODIFY ("MAPY" CONSTRAINT "MAPY2" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."ACCOMMODATION" MODIFY ("TITLE" CONSTRAINT "TITLE2_NN" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."ACCOMMODATION" ADD PRIMARY KEY ("ACC_IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
