--------------------------------------------------------
--  파일이 생성됨 - 금요일-4월-11-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BBS
--------------------------------------------------------

  CREATE TABLE "ADMIN"."BBS" 
   (	"FILE_DETAIL_ID" NUMBER, 
	"FILE_MST_ID" NUMBER, 
	"FILE_DEST" NVARCHAR2(100), 
	"FILE_NUMBER" NUMBER, 
	"FILE_LOCATION" VARCHAR2(1000 BYTE), 
	"FILE_PATH" VARCHAR2(1000 BYTE), 
	"FILE_NAME" VARCHAR2(255 BYTE), 
	"ORG_FILE_NAME" VARCHAR2(255 BYTE), 
	"FILE_EXT" VARCHAR2(2 BYTE), 
	"FILE_MIME" VARCHAR2(100 BYTE), 
	"FILE_SIZE" NUMBER, 
	"REGID" VARCHAR2(30 BYTE), 
	"REGDATE" DATE DEFAULT SYSDATE, 
	"UPDID" VARCHAR2(30 BYTE), 
	"UPDDATE" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
REM INSERTING into ADMIN.BBS
SET DEFINE OFF;
--------------------------------------------------------
--  Constraints for Table BBS
--------------------------------------------------------

  ALTER TABLE "ADMIN"."BBS" MODIFY ("FILE_DETAIL_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."BBS" MODIFY ("FILE_MST_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."BBS" MODIFY ("FILE_LOCATION" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."BBS" MODIFY ("FILE_PATH" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."BBS" MODIFY ("FILE_NAME" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."BBS" MODIFY ("ORG_FILE_NAME" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."BBS" MODIFY ("FILE_EXT" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."BBS" MODIFY ("FILE_MIME" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."BBS" MODIFY ("FILE_SIZE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."BBS" MODIFY ("REGID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."BBS" MODIFY ("REGDATE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."BBS" MODIFY ("UPDID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."BBS" MODIFY ("UPDDATE" NOT NULL ENABLE);
