--------------------------------------------------------
--  파일이 생성됨 - 금요일-4월-11-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BOARD
--------------------------------------------------------

  CREATE TABLE "ADMIN"."BOARD" 
   (	"BOD_IDX" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"CATE" NUMBER(4,0), 
	"BOD_TITLE" NVARCHAR2(50), 
	"BOD_CONSTENT" NVARCHAR2(2000), 
	"TRAVEL_START_DATE" DATE, 
	"TRAVEL_END_DATE" DATE, 
	"VISIT" DATE, 
	"FES_TITLE" NVARCHAR2(100), 
	"ACC_TITLE" NVARCHAR2(100), 
	"RATING" NUMBER(1,0), 
	"REG_IDX" NUMBER, 
	"REG2_DATE" DATE DEFAULT SYSDATE, 
	"UPDATE_IDX" NUMBER, 
	"UPDATE_DATE" DATE DEFAULT SYSDATE, 
	"FILE_MST_ID" NVARCHAR2(15), 
	"USER_ID" NVARCHAR2(10)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
REM INSERTING into ADMIN.BOARD
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index BOD_USER_ID_UNI
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."BOD_USER_ID_UNI" ON "ADMIN"."BOARD" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008728
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."SYS_C008728" ON "ADMIN"."BOARD" ("BOD_IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table BOARD
--------------------------------------------------------

  ALTER TABLE "ADMIN"."BOARD" MODIFY ("BOD_IDX" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."BOARD" MODIFY ("CATE" CONSTRAINT "CATE_NN" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."BOARD" MODIFY ("BOD_TITLE" CONSTRAINT "BOD_TITLE_NN" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."BOARD" MODIFY ("BOD_CONSTENT" CONSTRAINT "BOD_CONSTENT_NN" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."BOARD" MODIFY ("TRAVEL_START_DATE" CONSTRAINT "TRAVEL_START_DATE_NN" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."BOARD" MODIFY ("TRAVEL_END_DATE" CONSTRAINT "TRAVEL_END_DATE_NN" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."BOARD" MODIFY ("VISIT" CONSTRAINT "VISIT_NN" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."BOARD" MODIFY ("FES_TITLE" CONSTRAINT "FES_TITLE_NN" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."BOARD" MODIFY ("ACC_TITLE" CONSTRAINT "ACC_TITLE_NN" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."BOARD" MODIFY ("RATING" CONSTRAINT "RATING_NN" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."BOARD" MODIFY ("REG_IDX" CONSTRAINT "REGID_NN" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."BOARD" MODIFY ("REG2_DATE" CONSTRAINT "REG2_DATE_NN" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."BOARD" MODIFY ("UPDATE_IDX" CONSTRAINT "UPDATE_ID_NN" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."BOARD" MODIFY ("UPDATE_DATE" CONSTRAINT "UPDATE_DATE_NN" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."BOARD" ADD PRIMARY KEY ("BOD_IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ADMIN"."BOARD" ADD CONSTRAINT "BOD_USER_ID_UNI" UNIQUE ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ADMIN"."BOARD" MODIFY ("USER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table BOARD
--------------------------------------------------------

  ALTER TABLE "ADMIN"."BOARD" ADD CONSTRAINT "BOARD_MEMBER_FK" FOREIGN KEY ("USER_ID")
	  REFERENCES "ADMIN"."MEMBER" ("USER_ID") ENABLE;
