--------------------------------------------------------
--  파일이 생성됨 - 금요일-4월-11-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table COMMENTS
--------------------------------------------------------

  CREATE TABLE "ADMIN"."COMMENTS" 
   (	"COM_IDX" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"CONTENT" NVARCHAR2(500), 
	"REG_ID" NVARCHAR2(30), 
	"REG_DATE" DATE DEFAULT SYSDATE, 
	"UPD_ID" NVARCHAR2(30), 
	"UPD_DATE" DATE DEFAULT SYSDATE, 
	"USER_ID" NVARCHAR2(10)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
REM INSERTING into ADMIN.COMMENTS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index COM_USER_ID_UNI
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."COM_USER_ID_UNI" ON "ADMIN"."COMMENTS" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008629
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."SYS_C008629" ON "ADMIN"."COMMENTS" ("COM_IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table COMMENTS
--------------------------------------------------------

  ALTER TABLE "ADMIN"."COMMENTS" MODIFY ("COM_IDX" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."COMMENTS" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."COMMENTS" MODIFY ("REG_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."COMMENTS" MODIFY ("REG_DATE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."COMMENTS" MODIFY ("UPD_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."COMMENTS" MODIFY ("UPD_DATE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."COMMENTS" ADD PRIMARY KEY ("COM_IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ADMIN"."COMMENTS" ADD CONSTRAINT "COM_USER_ID_UNI" UNIQUE ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ADMIN"."COMMENTS" MODIFY ("USER_ID" NOT NULL ENABLE);
