--------------------------------------------------------
--  파일이 생성됨 - 금요일-4월-11-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table FESTIVAL
--------------------------------------------------------

  CREATE TABLE "ADMIN"."FESTIVAL" 
   (	"FES_IDX" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"AREA_CODE" NUMBER(3,0), 
	"ADDR" NVARCHAR2(50), 
	"ADDR_2" NVARCHAR2(50), 
	"MAPX" NUMBER(13,10), 
	"MAPY" NUMBER(13,10), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"TITLE" NVARCHAR2(30), 
	"TEL" NVARCHAR2(20), 
	"IMAGE" VARCHAR2(100 BYTE), 
	"IMAGE_2" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
REM INSERTING into ADMIN.FESTIVAL
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index SYS_C008597
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."SYS_C008597" ON "ADMIN"."FESTIVAL" ("FES_IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table FESTIVAL
--------------------------------------------------------

  ALTER TABLE "ADMIN"."FESTIVAL" MODIFY ("FES_IDX" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."FESTIVAL" MODIFY ("AREA_CODE" CONSTRAINT "AREA_CODE_NN" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."FESTIVAL" MODIFY ("ADDR" CONSTRAINT "ADDR_NN" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."FESTIVAL" MODIFY ("MAPX" CONSTRAINT "MAPX" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."FESTIVAL" MODIFY ("MAPY" CONSTRAINT "MAPY" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."FESTIVAL" MODIFY ("START_DATE" CONSTRAINT "START_DATE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."FESTIVAL" MODIFY ("END_DATE" CONSTRAINT "END_DATE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."FESTIVAL" MODIFY ("TITLE" CONSTRAINT "TITLE_NN" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."FESTIVAL" MODIFY ("IMAGE" CONSTRAINT "IMAGE_NN" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."FESTIVAL" ADD PRIMARY KEY ("FES_IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
