--------------------------------------------------------
--  파일이 생성됨 - 금요일-4월-11-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "ADMIN"."MEMBER" 
   (	"MEM_IDX" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"IS_ADMIN" NUMBER(1,0) DEFAULT 0, 
	"USER_PW" CHAR(64 BYTE), 
	"USER_NAME" NVARCHAR2(10), 
	"EMAIL" NVARCHAR2(30), 
	"PHONE_NUM" NUMBER(13,0), 
	"REG_DATE" DATE DEFAULT SYSDATE, 
	"DROP_DATE" DATE DEFAULT SYSDATE, 
	"USER_ADDR" NVARCHAR2(50), 
	"DROP_YN" CHAR(1 BYTE) DEFAULT 'N', 
	"EMAIL_AUTH" CHAR(1 BYTE) DEFAULT 'N', 
	"EMAIL_AUTH_CODE" NVARCHAR2(50), 
	"BLOCK_CODE" CHAR(1 BYTE) DEFAULT 'N', 
	"USER_ID" NVARCHAR2(10)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
REM INSERTING into ADMIN.MEMBER
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index SYS_C008679
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."SYS_C008679" ON "ADMIN"."MEMBER" ("MEM_IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MEM_USER_ID_UNI
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."MEM_USER_ID_UNI" ON "ADMIN"."MEMBER" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "ADMIN"."MEMBER" MODIFY ("MEM_IDX" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MEMBER" MODIFY ("IS_ADMIN" CONSTRAINT "IS_ADMIN_NN" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MEMBER" MODIFY ("USER_PW" CONSTRAINT "USER_PW_NN" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MEMBER" MODIFY ("USER_NAME" CONSTRAINT "USER_NAME_NN" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MEMBER" MODIFY ("EMAIL" CONSTRAINT "EMAIL_NN" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MEMBER" MODIFY ("PHONE_NUM" CONSTRAINT "PHONE_NUM_NN" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MEMBER" MODIFY ("REG_DATE" CONSTRAINT "REG_DATE_NN" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MEMBER" MODIFY ("DROP_DATE" CONSTRAINT "DROP_DATE_NN" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MEMBER" MODIFY ("DROP_YN" CONSTRAINT "DROP_YN_NN" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MEMBER" MODIFY ("EMAIL_AUTH" CONSTRAINT "EMAIL_AUTH_NN" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MEMBER" MODIFY ("EMAIL_AUTH_CODE" CONSTRAINT "EMAIL_AUTH_CODE_NN" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MEMBER" MODIFY ("BLOCK_CODE" CONSTRAINT "BLOCK_CODE_NN" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MEMBER" ADD PRIMARY KEY ("MEM_IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ADMIN"."MEMBER" ADD CONSTRAINT "MEM_USER_ID_UNI" UNIQUE ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ADMIN"."MEMBER" ADD CONSTRAINT "USER_ID_NN" CHECK ("USER_ID"IS NOT NULL) ENABLE;
  ALTER TABLE "ADMIN"."MEMBER" MODIFY ("USER_ID" NOT NULL ENABLE);
