--------------------------------------------------------
--  파일이 생성됨 - 월요일-4월-14-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ACCOMMODATION
--------------------------------------------------------

  CREATE TABLE "ADMIN"."ACCOMMODATION" 
   (	"ACC_IDX" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"AREA_CODE" NUMBER(3,0), 
	"ADDR" NVARCHAR2(50), 
	"ADDR_2" NVARCHAR2(50), 
	"MAPX" NUMBER(13,10), 
	"MAPY" NUMBER(13,10), 
	"TITLE" NVARCHAR2(30), 
	"TEL" NVARCHAR2(20), 
	"IMAGE" VARCHAR2(100 BYTE), 
	"IMAGE_2" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BBS
--------------------------------------------------------

  CREATE TABLE "ADMIN"."BBS" 
   (	"FILE_DETAIL_ID" NUMBER, 
	"FILE_MST_ID" NUMBER, 
	"FILE_DEST" NVARCHAR2(100), 
	"FILE_NUMBER" NUMBER, 
	"FILE_LOCATION" VARCHAR2(1000 BYTE), 
	"FILE_PATH" VARCHAR2(1000 BYTE), 
	"FILE_NAME" VARCHAR2(255 BYTE), 
	"ORG_FILE_NAME" VARCHAR2(255 BYTE), 
	"FILE_EXT" VARCHAR2(2 BYTE), 
	"FILE_MIME" VARCHAR2(100 BYTE), 
	"FILE_SIZE" NUMBER, 
	"REGID" VARCHAR2(30 BYTE), 
	"REGDATE" TIMESTAMP (6) DEFAULT SYSDATE, 
	"UPDID" VARCHAR2(30 BYTE), 
	"UPDDATE" TIMESTAMP (6) DEFAULT SYSDATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BOARD_DEFAULT
--------------------------------------------------------

  CREATE TABLE "ADMIN"."BOARD_DEFAULT" 
   (	"BOD_IDX" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"CATE" NUMBER(4,0), 
	"BOD_TITLE" NVARCHAR2(50), 
	"BOD_CONSTENT" NVARCHAR2(2000), 
	"REG_ID" NVARCHAR2(30), 
	"REG2_DATE" TIMESTAMP (6) DEFAULT SYSDATE, 
	"UPDATE_ID" NVARCHAR2(30), 
	"UPDATE_DATE" TIMESTAMP (6) DEFAULT SYSDATE, 
	"FILE_MST_ID" NVARCHAR2(15), 
	"USER_ID" NVARCHAR2(10), 
	"IS_VISIBLE" CHAR(1 BYTE) DEFAULT 'N', 
	"USER_CNT" NUMBER(38,0) DEFAULT 0, 
	"FES_TITLE" NVARCHAR2(100), 
	"ACC_TITLE" NVARCHAR2(100)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BOARD_REVIEW
--------------------------------------------------------

  CREATE TABLE "ADMIN"."BOARD_REVIEW" 
   (	"BOD_IDX" NUMBER, 
	"RATING" NUMBER(1,0), 
	"VISIT_DATE" TIMESTAMP (6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BOARD_SHARE
--------------------------------------------------------

  CREATE TABLE "ADMIN"."BOARD_SHARE" 
   (	"BOD_IDX" NUMBER, 
	"TRAVEL_START_DATE" TIMESTAMP (6), 
	"TRAVEL_END_DATE" TIMESTAMP (6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table COMMENTS
--------------------------------------------------------

  CREATE TABLE "ADMIN"."COMMENTS" 
   (	"COM_IDX" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"CONTENT" NVARCHAR2(500), 
	"REG_ID" NVARCHAR2(30), 
	"REG_DATE" TIMESTAMP (6) DEFAULT SYSDATE, 
	"UPD_ID" NVARCHAR2(30), 
	"UPD_DATE" TIMESTAMP (6) DEFAULT SYSDATE, 
	"USER_ID" NVARCHAR2(10), 
	"BOD_IDX" NUMBER, 
	"IS_VISIBLE" CHAR(1 BYTE) DEFAULT 'N'
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FESTIVAL
--------------------------------------------------------

  CREATE TABLE "ADMIN"."FESTIVAL" 
   (	"FES_IDX" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"AREA_CODE" NUMBER(3,0), 
	"ADDR" NVARCHAR2(50), 
	"ADDR_2" NVARCHAR2(50), 
	"MAPX" NUMBER(13,10), 
	"MAPY" NUMBER(13,10), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"TITLE" NVARCHAR2(30), 
	"TEL" NVARCHAR2(20), 
	"IMAGE" VARCHAR2(100 BYTE), 
	"IMAGE_2" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "ADMIN"."MEMBER" 
   (	"IS_ADMIN" NUMBER(1,0) DEFAULT 0, 
	"USER_PW" CHAR(64 BYTE), 
	"USER_NAME" NVARCHAR2(10), 
	"EMAIL" NVARCHAR2(30), 
	"PHONE_NUM" VARCHAR2(13 BYTE), 
	"REG_DATE" DATE DEFAULT SYSDATE, 
	"DROP_DATE" DATE DEFAULT SYSDATE, 
	"USER_ADDR" NVARCHAR2(50), 
	"DROP_YN" CHAR(1 BYTE) DEFAULT 'N', 
	"EMAIL_AUTH" CHAR(1 BYTE) DEFAULT 'N', 
	"EMAIL_AUTH_CODE" NVARCHAR2(64), 
	"BLOCK_CODE" CHAR(1 BYTE) DEFAULT 'N', 
	"USER_ID" NVARCHAR2(10)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into ADMIN.ACCOMMODATION
SET DEFINE OFF;
Insert into ADMIN.ACCOMMODATION (ACC_IDX,AREA_CODE,ADDR,ADDR_2,MAPX,MAPY,TITLE,TEL,IMAGE,IMAGE_2) values (1,1,'경상북도 안동시 하회남촌길 69-5',null,128.5175868107,36.537653745,'가경재','-9353','http://tong.visitkorea.or.kr/cms/resource/00/2626200_image2_1.jpg','http://tong.visitkorea.or.kr/cms/resource/00/2626200_image3_1.jpg');
REM INSERTING into ADMIN.BBS
SET DEFINE OFF;
REM INSERTING into ADMIN.BOARD_DEFAULT
SET DEFINE OFF;
REM INSERTING into ADMIN.BOARD_REVIEW
SET DEFINE OFF;
REM INSERTING into ADMIN.BOARD_SHARE
SET DEFINE OFF;
REM INSERTING into ADMIN.COMMENTS
SET DEFINE OFF;
REM INSERTING into ADMIN.FESTIVAL
SET DEFINE OFF;
Insert into ADMIN.FESTIVAL (FES_IDX,AREA_CODE,ADDR,ADDR_2,MAPX,MAPY,START_DATE,END_DATE,TITLE,TEL,IMAGE,IMAGE_2) values (1,1,'서울특별시 송파구 양재대로 932 (가락동)','가락몰 3층 하늘공원',127.1107693087,37.4960786971,to_date('25/05/09','RR/MM/DD'),to_date('25/05/11','RR/MM/DD'),'가락몰 빵축제 전국빵지자랑','02-3435-0286','http://tong.visitkorea.or.kr/cms/resource/91/3484791_image2_1.jpg','http://tong.visitkorea.or.kr/cms/resource/91/3484791_image3_1.jpg');
REM INSERTING into ADMIN.MEMBER
SET DEFINE OFF;
Insert into ADMIN.MEMBER (IS_ADMIN,USER_PW,USER_NAME,EMAIL,PHONE_NUM,REG_DATE,DROP_DATE,USER_ADDR,DROP_YN,EMAIL_AUTH,EMAIL_AUTH_CODE,BLOCK_CODE,USER_ID) values (0,'DB8D6F07601A8AFCFD664ECDAF1B0280974D1B3DBF1D17695958C0165BA29256','김구','kimgu@naver.com','010-1234-1456',to_date('25/04/11','RR/MM/DD'),to_date('25/04/11','RR/MM/DD'),'서울시 용산구','N','N','EE425DF98582637BAC95ED97CBF450C593D75E34CF832FD8ACB5913392C52DD8','N','KIMGU');
--------------------------------------------------------
--  DDL for Index ACCOMMODATION_ADDR_IDX
--------------------------------------------------------

  CREATE INDEX "ADMIN"."ACCOMMODATION_ADDR_IDX" ON "ADMIN"."ACCOMMODATION" ("ADDR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ACCOMMODATION_TITLE_IDX
--------------------------------------------------------

  CREATE INDEX "ADMIN"."ACCOMMODATION_TITLE_IDX" ON "ADMIN"."ACCOMMODATION" ("TITLE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008607
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."SYS_C008607" ON "ADMIN"."ACCOMMODATION" ("ACC_IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_BOARD_DEFAULT
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."PK_BOARD_DEFAULT" ON "ADMIN"."BOARD_DEFAULT" ("BOD_IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_BOARD_REVIEW
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."PK_BOARD_REVIEW" ON "ADMIN"."BOARD_REVIEW" ("BOD_IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_BOARD_SHARE
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."PK_BOARD_SHARE" ON "ADMIN"."BOARD_SHARE" ("BOD_IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index COM_USER_ID_UNI
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."COM_USER_ID_UNI" ON "ADMIN"."COMMENTS" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008629
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."SYS_C008629" ON "ADMIN"."COMMENTS" ("COM_IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FESTIVAL_END_DATE_IDX
--------------------------------------------------------

  CREATE INDEX "ADMIN"."FESTIVAL_END_DATE_IDX" ON "ADMIN"."FESTIVAL" ("END_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FESTIVAL_MAPX_IDX
--------------------------------------------------------

  CREATE INDEX "ADMIN"."FESTIVAL_MAPX_IDX" ON "ADMIN"."FESTIVAL" ("MAPX", "MAPY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FESTIVAL_ADDR_IDX
--------------------------------------------------------

  CREATE INDEX "ADMIN"."FESTIVAL_ADDR_IDX" ON "ADMIN"."FESTIVAL" ("ADDR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008597
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."SYS_C008597" ON "ADMIN"."FESTIVAL" ("FES_IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FESTIVAL_START_DATE_IDX
--------------------------------------------------------

  CREATE INDEX "ADMIN"."FESTIVAL_START_DATE_IDX" ON "ADMIN"."FESTIVAL" ("START_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FESTIVAL_TITLE_IDX
--------------------------------------------------------

  CREATE INDEX "ADMIN"."FESTIVAL_TITLE_IDX" ON "ADMIN"."FESTIVAL" ("TITLE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MEMBER_PHONE_NUM_IDX
--------------------------------------------------------

  CREATE INDEX "ADMIN"."MEMBER_PHONE_NUM_IDX" ON "ADMIN"."MEMBER" ("PHONE_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MEMBER_REG_DATE_IDX
--------------------------------------------------------

  CREATE INDEX "ADMIN"."MEMBER_REG_DATE_IDX" ON "ADMIN"."MEMBER" ("REG_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MEMBER_DROP_DATE_IDX
--------------------------------------------------------

  CREATE INDEX "ADMIN"."MEMBER_DROP_DATE_IDX" ON "ADMIN"."MEMBER" ("DROP_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MEMBER_USER_ID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."MEMBER_USER_ID_PK" ON "ADMIN"."MEMBER" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MEMBER_EMAIL_IDX
--------------------------------------------------------

  CREATE INDEX "ADMIN"."MEMBER_EMAIL_IDX" ON "ADMIN"."MEMBER" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ACCOMMODATION
--------------------------------------------------------

  ALTER TABLE "ADMIN"."ACCOMMODATION" MODIFY ("ACC_IDX" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."ACCOMMODATION" MODIFY ("AREA_CODE" CONSTRAINT "AREA2_CODE_NN" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."ACCOMMODATION" MODIFY ("ADDR" CONSTRAINT "ADDR2_NN" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."ACCOMMODATION" MODIFY ("MAPX" CONSTRAINT "MAPX2" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."ACCOMMODATION" MODIFY ("MAPY" CONSTRAINT "MAPY2" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."ACCOMMODATION" MODIFY ("TITLE" CONSTRAINT "TITLE2_NN" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."ACCOMMODATION" ADD PRIMARY KEY ("ACC_IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BBS
--------------------------------------------------------

  ALTER TABLE "ADMIN"."BBS" MODIFY ("FILE_DETAIL_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."BBS" MODIFY ("FILE_MST_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."BBS" MODIFY ("FILE_LOCATION" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."BBS" MODIFY ("FILE_PATH" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."BBS" MODIFY ("FILE_NAME" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."BBS" MODIFY ("ORG_FILE_NAME" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."BBS" MODIFY ("FILE_EXT" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."BBS" MODIFY ("FILE_MIME" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."BBS" MODIFY ("FILE_SIZE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."BBS" MODIFY ("REGID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."BBS" MODIFY ("REGDATE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."BBS" MODIFY ("UPDID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."BBS" MODIFY ("UPDDATE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BOARD_DEFAULT
--------------------------------------------------------

  ALTER TABLE "ADMIN"."BOARD_DEFAULT" MODIFY ("BOD_IDX" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."BOARD_DEFAULT" MODIFY ("CATE" CONSTRAINT "BOARD_DEFAULT_CATE_NN" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."BOARD_DEFAULT" MODIFY ("BOD_TITLE" CONSTRAINT "BOARD_DEFAULT_BOD_TITLE_NN" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."BOARD_DEFAULT" MODIFY ("BOD_CONSTENT" CONSTRAINT "BOARD_DEFAULT_BOD_CONSTENT_NN" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."BOARD_DEFAULT" MODIFY ("REG_ID" CONSTRAINT "BOARD_DEFAULT_REG_ID_NN" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."BOARD_DEFAULT" MODIFY ("REG2_DATE" CONSTRAINT "BOARD_DEFAULT_REG2_DATE_NN" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."BOARD_DEFAULT" MODIFY ("UPDATE_ID" CONSTRAINT "BOARD_DEFAULT_UPDATE_ID_NN" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."BOARD_DEFAULT" MODIFY ("UPDATE_DATE" CONSTRAINT "BOARD_DEFAULT_UPDATE_DATE_NN" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."BOARD_DEFAULT" MODIFY ("USER_ID" CONSTRAINT "BOARD_DEFAULT_USER_ID_NN" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."BOARD_DEFAULT" MODIFY ("IS_VISIBLE" CONSTRAINT "BOARD_DEFAULT_IS_VISIBLE_NN" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."BOARD_DEFAULT" MODIFY ("USER_CNT" CONSTRAINT "BOARD_DEFAULT_USER_CNT_NN" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."BOARD_DEFAULT" ADD CONSTRAINT "PK_BOARD_DEFAULT" PRIMARY KEY ("BOD_IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ADMIN"."BOARD_DEFAULT" ADD CONSTRAINT "BOARD_DEFAULT_IS_VISIBLE_CHK" CHECK (IS_VISIBLE IN ('Y', 'N')) ENABLE;
--------------------------------------------------------
--  Constraints for Table BOARD_REVIEW
--------------------------------------------------------

  ALTER TABLE "ADMIN"."BOARD_REVIEW" MODIFY ("BOD_IDX" CONSTRAINT "BOARD_REVIEW_BOD_IDX_NN" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."BOARD_REVIEW" MODIFY ("RATING" CONSTRAINT "BOARD_REVIEW_RATING_NN" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."BOARD_REVIEW" MODIFY ("VISIT_DATE" CONSTRAINT "BOARD_REVIEW_VISIT_NN" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."BOARD_REVIEW" ADD CONSTRAINT "BOARD_REVIEW_RATING_RANGE" CHECK (RATING BETWEEN 1 AND 5) ENABLE;
  ALTER TABLE "ADMIN"."BOARD_REVIEW" ADD CONSTRAINT "PK_BOARD_REVIEW" PRIMARY KEY ("BOD_IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BOARD_SHARE
--------------------------------------------------------

  ALTER TABLE "ADMIN"."BOARD_SHARE" MODIFY ("BOD_IDX" CONSTRAINT "BOARD_SHARE_BOD_IDX_NN" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."BOARD_SHARE" MODIFY ("TRAVEL_START_DATE" CONSTRAINT "BOARD_SHARE_START_NN" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."BOARD_SHARE" MODIFY ("TRAVEL_END_DATE" CONSTRAINT "BOARD_SHARE_END_NN" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."BOARD_SHARE" ADD CONSTRAINT "PK_BOARD_SHARE" PRIMARY KEY ("BOD_IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COMMENTS
--------------------------------------------------------

  ALTER TABLE "ADMIN"."COMMENTS" MODIFY ("COM_IDX" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."COMMENTS" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."COMMENTS" MODIFY ("REG_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."COMMENTS" MODIFY ("REG_DATE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."COMMENTS" MODIFY ("UPD_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."COMMENTS" MODIFY ("UPD_DATE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."COMMENTS" ADD PRIMARY KEY ("COM_IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ADMIN"."COMMENTS" ADD CONSTRAINT "COM_USER_ID_UNI" UNIQUE ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ADMIN"."COMMENTS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."COMMENTS" MODIFY ("BOD_IDX" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."COMMENTS" MODIFY ("IS_VISIBLE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FESTIVAL
--------------------------------------------------------

  ALTER TABLE "ADMIN"."FESTIVAL" MODIFY ("FES_IDX" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."FESTIVAL" MODIFY ("AREA_CODE" CONSTRAINT "AREA_CODE_NN" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."FESTIVAL" MODIFY ("ADDR" CONSTRAINT "ADDR_NN" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."FESTIVAL" MODIFY ("MAPX" CONSTRAINT "MAPX" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."FESTIVAL" MODIFY ("MAPY" CONSTRAINT "MAPY" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."FESTIVAL" MODIFY ("START_DATE" CONSTRAINT "START_DATE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."FESTIVAL" MODIFY ("END_DATE" CONSTRAINT "END_DATE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."FESTIVAL" MODIFY ("TITLE" CONSTRAINT "TITLE_NN" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."FESTIVAL" MODIFY ("IMAGE" CONSTRAINT "IMAGE_NN" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."FESTIVAL" ADD PRIMARY KEY ("FES_IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "ADMIN"."MEMBER" MODIFY ("IS_ADMIN" CONSTRAINT "IS_ADMIN_NN" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MEMBER" MODIFY ("USER_PW" CONSTRAINT "USER_PW_NN" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MEMBER" MODIFY ("USER_NAME" CONSTRAINT "USER_NAME_NN" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MEMBER" MODIFY ("EMAIL" CONSTRAINT "EMAIL_NN" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MEMBER" MODIFY ("PHONE_NUM" CONSTRAINT "PHONE_NUM_NN" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MEMBER" MODIFY ("REG_DATE" CONSTRAINT "REG_DATE_NN" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MEMBER" MODIFY ("DROP_DATE" CONSTRAINT "DROP_DATE_NN" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MEMBER" MODIFY ("DROP_YN" CONSTRAINT "DROP_YN_NN" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MEMBER" MODIFY ("EMAIL_AUTH" CONSTRAINT "EMAIL_AUTH_NN" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MEMBER" MODIFY ("EMAIL_AUTH_CODE" CONSTRAINT "EMAIL_AUTH_CODE_NN" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MEMBER" MODIFY ("BLOCK_CODE" CONSTRAINT "BLOCK_CODE_NN" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MEMBER" ADD CONSTRAINT "MEMBER_USER_ID_PK" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ADMIN"."MEMBER" ADD CONSTRAINT "USER_ID_NN" CHECK ("USER_ID"IS NOT NULL) ENABLE;
  ALTER TABLE "ADMIN"."MEMBER" MODIFY ("USER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table BOARD_DEFAULT
--------------------------------------------------------

  ALTER TABLE "ADMIN"."BOARD_DEFAULT" ADD CONSTRAINT "FK_BOARD_DEFAULT_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "ADMIN"."MEMBER" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BOARD_REVIEW
--------------------------------------------------------

  ALTER TABLE "ADMIN"."BOARD_REVIEW" ADD CONSTRAINT "FK_BOARD_REVIEW_BOARD" FOREIGN KEY ("BOD_IDX")
	  REFERENCES "ADMIN"."BOARD_DEFAULT" ("BOD_IDX") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BOARD_SHARE
--------------------------------------------------------

  ALTER TABLE "ADMIN"."BOARD_SHARE" ADD CONSTRAINT "FK_BOARD_SHARE_BOARD" FOREIGN KEY ("BOD_IDX")
	  REFERENCES "ADMIN"."BOARD_DEFAULT" ("BOD_IDX") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMMENTS
--------------------------------------------------------

  ALTER TABLE "ADMIN"."COMMENTS" ADD CONSTRAINT "COMMENTS_BOARD_DEFAULT_FK" FOREIGN KEY ("BOD_IDX")
	  REFERENCES "ADMIN"."BOARD_DEFAULT" ("BOD_IDX") ENABLE;
  ALTER TABLE "ADMIN"."COMMENTS" ADD CONSTRAINT "COMMENTS_MEMBER_FK" FOREIGN KEY ("USER_ID")
	  REFERENCES "ADMIN"."MEMBER" ("USER_ID") ENABLE;
