-- 테이블 설정
CREATE TABLE comments (
    idx         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 고유번호
    content     NVARCHAR2(2000) NOT NULL,                             -- 내용
    regID       NVARCHAR2(30) NOT NULL,                               -- 등록자ID
    regDate     TIMESTAMP DEFAULT SYSDATE NOT NULL,                   -- 등록일
    updID       NVARCHAR2(30) NOT NULL,                               -- 수정자ID
    updDate     TIMESTAMP DEFAULT SYSDATE NOT NULL,                   -- 수정일
    USER_ID     NVARCHAR2(10) NOT NULL,                               -- 등록자 ID
    rating      NUMBER(1,0) DEFAULT 0 NOT NULL,                       -- 리뷰 점수 1~5
    GAME_IDX    NUMBER NOT NULL,                                      -- 게임 고유번호 (FK)
    IS_VISIBLE  NUMBER(1,0) DEFAULT 0 NOT NULL                        -- 보이기 여부
);

-- 📌 컬럼별 설명
COMMENT ON TABLE comments IS '게임플랫폼 이용자 리뷰 및 코멘트';

COMMENT ON COLUMN comments.idx        IS '고유번호';
COMMENT ON COLUMN comments.content    IS '내용';
COMMENT ON COLUMN comments.regID      IS '등록자ID';
COMMENT ON COLUMN comments.regDate    IS '등록일';
COMMENT ON COLUMN comments.updID      IS '수정자ID';
COMMENT ON COLUMN comments.updDate    IS '수정일';
COMMENT ON COLUMN comments.USER_ID    IS '등록자 ID : MEMBER_USER_ID_FK';
COMMENT ON COLUMN comments.rating     IS '게임 리뷰 별점 1~5까지';
COMMENT ON COLUMN comments.GAME_IDX   IS '게임 고유번호 : GAME_IDX_FK';
COMMENT ON COLUMN comments.IS_VISIBLE IS '불량 코멘트 감추기 0: 보이기 1: 감추기';
