-- 테이블 생성
CREATE TABLE MEMBER (
    IS_ADMIN           NUMBER(1,0)     DEFAULT 0     NOT NULL,
    USER_ID            NVARCHAR2(10)                NOT NULL,
    USER_PW            NVARCHAR2(100)               NOT NULL,
    USER_NAME          NVARCHAR2(10)                NOT NULL,
    EMAIL              NVARCHAR2(30)                NOT NULL,
    PHONE_NUM          NUMBER(13,0)                 NOT NULL,
    REG_DATE           DATE           DEFAULT SYSDATE NOT NULL,
    DROP_DATE          DATE           DEFAULT SYSDATE NOT NULL,
    DROP_YN            NUMBER(1,0)     DEFAULT 0     NOT NULL,
    EMAIL_AUTH         NUMBER(1,0)     DEFAULT 0     NOT NULL,
    EMAIL_AUTH_CODE    NVARCHAR2(50)               NOT NULL,
    BLOCK_CODE         NUMBER(1,0)     DEFAULT 0     NOT NULL,
    BIRTH_DATE         NVARCHAR2(10)               NOT NULL
    CONSTRAINT MEMBER_PK PRIMARY KEY (USER_ID) ENABLE;
);

-- 컬럼 코멘트 추가
COMMENT ON TABLE MEMBER IS '게임플랫폼 / 사용자';

COMMENT ON COLUMN MEMBER.IS_ADMIN IS '관리자 여부 0: 사용자 1: 관리자';
COMMENT ON COLUMN MEMBER.USER_ID IS '사용자ID';
COMMENT ON COLUMN MEMBER.USER_PW IS '사용자비번 SHA256';
COMMENT ON COLUMN MEMBER.USER_NAME IS '사용자이름';
COMMENT ON COLUMN MEMBER.EMAIL IS '사용자이메일';
COMMENT ON COLUMN MEMBER.PHONE_NUM IS '사용자 연락처';
COMMENT ON COLUMN MEMBER.REG_DATE IS '가입일';
COMMENT ON COLUMN MEMBER.DROP_DATE IS '탈퇴일';
COMMENT ON COLUMN MEMBER.DROP_YN IS '탈퇴여부 확인 0: 기본 1: 탈퇴신청';
COMMENT ON COLUMN MEMBER.EMAIL_AUTH IS '이메일 인증여부 0: 미인증 1: 인증';
COMMENT ON COLUMN MEMBER.EMAIL_AUTH_CODE IS '이메일 인증코드 SHA256';
COMMENT ON COLUMN MEMBER.BLOCK_CODE IS '불량회원 관리 0: 정상이용자 1: 불량이용자';
COMMENT ON COLUMN MEMBER.BIRTH_DATE IS '생년월일';
