CREATE TABLE REPORT (
    USER_ID   NVARCHAR2(10) NOT NULL,
    COM_IDX   NUMBER         NOT NULL
);

-- 주석 (COMMENT)
COMMENT ON TABLE REPORT IS '코멘트 신고';
COMMENT ON COLUMN REPORT.USER_ID IS '사용자 조회 MEMBER_USER_ID_FK';
COMMENT ON COLUMN REPORT.COM_IDX IS '조회 하기 위한 고유번호 COMMENTS_IDX_FK';
